spring.application.name=WeatherApplication

spring.datasource.url=jdbc:postgresql://localhost:5432/weather
spring.datasource.username=postgres
spring.datasource.password=kate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

secret.key=kate-is-planning-to-arrest-trapmaker-12344556566767787
